version: 2
updates:
  - package-ecosystem: cargo
    directory: /rust
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  # The libFuzzer graph has its own manifest and lockfile.
  - package-ecosystem: cargo
    directory: /rust/fuzz
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: rust-toolchain
    directory: /rust
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
