// The shared contract module.
//
// It holds the error taxonomy that crosses the FFI boundary and the vector
// loader that proves Android, iOS, and the CLI read one set of bytes. It holds
// no encoder: `docs/format/CANONICAL_ENCODING_V1.md` section 13 says Kotlin and
// Swift consume Rust-produced records and never define an alternate canonical
// encoder for a private format.

import java.security.MessageDigest

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.android.kmp.library)
}

kotlin {
    jvmToolchain(libs.versions.jdk.get().toInt())

    jvm()
    android {
        namespace = "dev.po4yka.chur.core.model"
        compileSdk = libs.versions.androidCompileSdk.get().toInt()
        minSdk = libs.versions.androidMinSdk.get().toInt()
        // The vector suite and the error mapping are host tests: they need no
        // device, and TEST_VECTORS.md section 7 wants them running on Android.
        withHostTest {}
    }
    iosArm64()
    iosSimulatorArm64()

    sourceSets {
        commonMain.dependencies {
            implementation(libs.kotlinx.serialization.json)
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
        }
    }
}

// ---------------------------------------------------------------------------
// Vector fixtures
// ---------------------------------------------------------------------------

/**
 * Embeds the checked-in vector set into a generated Kotlin source.
 *
 * `docs/format/TEST_VECTORS.md` section 7 requires the same suite to run in
 * Rust, the CLI, Android, and iOS. Reading files from a test differs per
 * platform and would make the iOS side read something else; generating one
 * Kotlin source from the repository files makes every target consume the same
 * bytes, and the manifest digest below makes a divergence a compile-time
 * change rather than a silent one.
 */
abstract class GenerateVectorFixtures : DefaultTask() {
    @get:InputDirectory
    abstract val vectorDirectory: DirectoryProperty

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val root = vectorDirectory.get().asFile
        val manifest = root.resolve("manifest.json")
        require(manifest.isFile) { "no manifest.json in ${root.absolutePath}" }

        val fixtures = root.walkTopDown()
            .filter { it.isFile && it.extension == "bin" }
            .map { it.relativeTo(root).invariantSeparatorsPath to sha256(it.readBytes()) }
            .sortedBy { it.first }
            .toList()

        val out = outputDirectory.get().asFile.resolve("dev/po4yka/chur/core/model/VectorFixtures.kt")
        out.parentFile.mkdirs()
        // A JVM class file caps one string constant at 65535 UTF-8 bytes and the
        // manifest is larger, so it is emitted as chunks that are joined at run
        // time. Concatenating them with `+` would be folded back into one
        // constant and hit the same cap.
        val chunks = manifest.readText().chunked(CHUNK_LENGTH)
        out.writeText(
            buildString {
                appendLine("// Generated by the :shared:core-model `generateVectorFixtures` task.")
                appendLine("// Source: test-vectors/v1. Do not edit; edit the vectors instead.")
                appendLine("//")
                appendLine("// TEST-ONLY — NEVER USE FOR REAL VAULTS.")
                appendLine()
                appendLine("package dev.po4yka.chur.core.model")
                appendLine()
                appendLine("/** The checked-in v1 vector set, embedded so every target reads one copy. */")
                appendLine("public object VectorFixtures {")
                appendLine("    private val MANIFEST_PARTS: List<String> = listOf(")
                chunks.forEach { chunk ->
                    appendLine("        ${escape(chunk)},")
                }
                appendLine("    )")
                appendLine()
                appendLine("    /** The exact bytes of `test-vectors/v1/manifest.json`. */")
                appendLine("    public val MANIFEST_JSON: String = MANIFEST_PARTS.joinToString(\"\")")
                appendLine()
                appendLine("    /** SHA-256 of the manifest, lowercase hexadecimal. */")
                appendLine("    public const val MANIFEST_DIGEST: String = \"${sha256(manifest.readBytes())}\"")
                appendLine()
                appendLine("    /** Every fixture file, by its path relative to `test-vectors/v1`. */")
                appendLine("    public val FIXTURE_DIGESTS: Map<String, String> = mapOf(")
                fixtures.forEach { (path, digest) ->
                    appendLine("        \"$path\" to \"$digest\",")
                }
                appendLine("    )")
                appendLine("}")
            }
        )
    }

    private fun escape(text: String): String =
        buildString {
            append('"')
            text.forEach { character ->
                when {
                    character == '\\' -> append("\\\\")
                    character == '"' -> append("\\\"")
                    character == '$' -> append("\\$")
                    character == '\n' -> append("\\n")
                    character == '\r' -> append("\\r")
                    character == '\t' -> append("\\t")
                    character.code < 0x20 -> append("\\u%04x".format(character.code))
                    else -> append(character)
                }
            }
            append('"')
        }

    private fun sha256(bytes: ByteArray): String =
        MessageDigest.getInstance("SHA-256")
            .digest(bytes)
            .joinToString("") { byte -> "%02x".format(byte) }

    private companion object {
        // Well under the 65535-byte constant cap even when every character
        // escapes to two bytes.
        const val CHUNK_LENGTH = 8000
    }
}

val generateVectorFixtures =
    tasks.register<GenerateVectorFixtures>("generateVectorFixtures") {
        description = "Embeds test-vectors/v1 into a generated Kotlin source."
        group = "build"
        vectorDirectory.set(rootProject.layout.projectDirectory.dir("test-vectors/v1"))
        outputDirectory.set(layout.buildDirectory.dir("generated/vectors"))
    }

kotlin.sourceSets.named("commonTest") {
    kotlin.srcDir(generateVectorFixtures)
}
